# Generated by Django 6.1.1 on 2026-10-10 20:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=False, help_text='Only active questions can be served to a game.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('topic', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('position', models.PositiveSmallIntegerField(help_text='Display position from 1 to 4.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='quiz.topic'),
        ),
        migrations.CreateModel(
            name='TopScoreRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('abandoned', 'Abandoned')], default='active', max_length=10)),
                ('end_reason', models.CharField(blank=True, choices=[('wrong_answer', 'Wrong answer'), ('timeout', 'Time expired'), ('quit', 'Player quit')], max_length=20)),
                ('score', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_score_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='TopScoreResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('response_time_ms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('is_correct', models.BooleanField(default=False, editable=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='top_score_responses', to='quiz.question')),
                ('selected_choice', models.ForeignKey(blank=True, help_text='Empty when the player ran out of time.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_score_selections', to='quiz.answerchoice')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quiz.topscorerun')),
            ],
            options={
                'ordering': ('sequence',),
            },
        ),
        migrations.AddConstraint(
            model_name='answerchoice',
            constraint=models.UniqueConstraint(fields=('question', 'position'), name='unique_choice_position_per_question'),
        ),
        migrations.AddConstraint(
            model_name='answerchoice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='at_most_one_correct_choice_per_question'),
        ),
        migrations.AddConstraint(
            model_name='answerchoice',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 4)), name='choice_position_between_1_and_4'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active', 'topic', 'difficulty'], name='quiz_questi_is_acti_164ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='topscorerun',
            index=models.Index(fields=['user', '-score'], name='quiz_topsco_user_id_9abe87_idx'),
        ),
        migrations.AddIndex(
            model_name='topscorerun',
            index=models.Index(fields=['status', 'started_at'], name='quiz_topsco_status_49fd79_idx'),
        ),
        migrations.AddConstraint(
            model_name='topscorerun',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='top_score_run_score_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='topscorerun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_reason', ''), ('ended_at__isnull', True), ('status', 'active')), models.Q(('ended_at__isnull', False), ('status__in', ('finished', 'abandoned'))), _connector='OR'), name='top_score_run_end_state_consistent'),
        ),
        migrations.AddConstraint(
            model_name='topscoreresponse',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='unique_response_sequence_per_run'),
        ),
        migrations.AddConstraint(
            model_name='topscoreresponse',
            constraint=models.UniqueConstraint(fields=('run', 'question'), name='question_once_per_top_score_run'),
        ),
        migrations.AddConstraint(
            model_name='topscoreresponse',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='top_score_response_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='topscoreresponse',
            constraint=models.CheckConstraint(condition=models.Q(('response_time_ms__gte', 0), ('response_time_ms__lte', 10000)), name='top_score_response_within_time_limit'),
        ),
    ]
