# Generated by Django 6.1.1 on 2026-10-10 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='topscoreresponse',
            name='question_once_per_top_score_run',
        ),
        migrations.AddField(
            model_name='topscorerun',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.question'),
        ),
        migrations.AddField(
            model_name='topscorerun',
            name='question_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
